import {
  TokenAmplunaIcon,
  TokenAtomIcon,
  TokenAxlusdcIcon,
  TokenBlurIcon,
  TokenBneoIcon,
  TokenBusdIcon,
  TokenEthIcon,
  TokenEvmosIcon,
  TokenGmxIcon,
  TokenIbcxIcon,
  TokenIrisIcon,
  TokenKujiIcon,
  TokenLsiIcon,
  TokenLunaIcon,
  TokenOkbIcon,
  TokenOktIcon,
  TokenOsmoIcon,
  TokenRatomIcon,
  TokenRswthIcon,
  TokenStatomIcon,
  TokenStevmosIcon,
  TokenStlunaIcon,
  TokenStosmoIcon,
  TokenStrdIcon,
  TokenSwthIcon,
  TokenUscIcon,
  TokenUsdIcon,
  TokenUsdcIcon,
  TokenWbtcIcon,
  TokenWstethIcon,
  TokenYieldUsdIcon,
  TokenZilIcon,
} from '@/icons';
import { IconProps } from '@/icons/withIconProps';
import { SupportedCurrencyEnum } from '@/types/currency';

export const ICON_BY_CURRENCY: Record<SupportedCurrencyEnum, React.ComponentType<IconProps>> = {
  ampLUNA: TokenAmplunaIcon,
  ATOM: TokenAtomIcon,
  axlUSDC: TokenAxlusdcIcon,
  BLUR: TokenBlurIcon,
  bNEO: TokenBneoIcon,
  BUSD: TokenBusdIcon,
  EVMOS: TokenEvmosIcon,
  GMX: TokenGmxIcon,
  IBCX: TokenIbcxIcon,
  IRIS: TokenIrisIcon,
  KUJI: TokenKujiIcon,
  LSI: TokenLsiIcon,
  LUNA: TokenLunaIcon,
  STEVMOS: TokenStevmosIcon,
  STRD: TokenStrdIcon,
  OKB: TokenOkbIcon,
  OKT: TokenOktIcon,
  OSMO: TokenOsmoIcon,
  RATOM: TokenRatomIcon,
  rSWTH: TokenRswthIcon,
  STATOM: TokenStatomIcon,
  STLUNA: TokenStlunaIcon,
  STOSMO: TokenStosmoIcon,
  SWTH: TokenSwthIcon,
  USC: TokenUscIcon,
  USD: TokenUsdIcon,
  USDC: TokenUsdcIcon,
  WBTC: TokenWbtcIcon,
  wstETH: TokenWstethIcon,
  YieldUSD: TokenYieldUsdIcon,
  ZIL: TokenZilIcon,
};
