import { withIconProps } from './withIconProps';

import { ReactComponent as Token1inch } from './tokens/1INCH.svg';
import { ReactComponent as TokenAave } from './tokens/AAVE.svg';
import { ReactComponent as TokenAda } from './tokens/ADA.svg';
import { ReactComponent as TokenAevo } from './tokens/AEVO.svg';
import { ReactComponent as TokenAgi } from './tokens/AGI.svg';
import { ReactComponent as TokenAkro } from './tokens/AKRO.svg';
import { ReactComponent as TokenAkt } from './tokens/AKT.svg';
import { ReactComponent as TokenAlgo } from './tokens/ALGO.svg';
import { ReactComponent as TokenAlpha } from './tokens/ALPHA.svg';
import { ReactComponent as TokenAmp } from './tokens/AMP.svg';
import { ReactComponent as TokenAnc } from './tokens/ANC.svg';
import { ReactComponent as TokenAnkr } from './tokens/ANKR.svg';
import { ReactComponent as TokenAnt } from './tokens/ANT.svg';
import { ReactComponent as TokenAny } from './tokens/ANY.svg';
import { ReactComponent as TokenApe } from './tokens/APE.svg';
import { ReactComponent as TokenApollo } from './tokens/APOLLO.svg';
import { ReactComponent as TokenAr } from './tokens/AR.svg';
import { ReactComponent as TokenArb } from './tokens/ARB.svg';
import { ReactComponent as TokenAsa } from './tokens/ASA.svg';
import { ReactComponent as TokenAstro } from './tokens/ASTRO.svg';
import { ReactComponent as TokenAtom } from './tokens/ATOM.svg';
import { ReactComponent as TokenAudio } from './tokens/AUDIO.svg';
import { ReactComponent as TokenAut } from './tokens/AUT.svg';
import { ReactComponent as TokenAva } from './tokens/AVA.svg';
import { ReactComponent as TokenAvax } from './tokens/AVAX.svg';
import { ReactComponent as TokenAxl } from './tokens/AXL.svg';
import { ReactComponent as TokenAxs } from './tokens/AXS.svg';
import { ReactComponent as TokenAxt } from './tokens/AXT.svg';
import { ReactComponent as TokenBake } from './tokens/BAKE.svg';
import { ReactComponent as TokenBal } from './tokens/BAL.svg';
import { ReactComponent as TokenBand } from './tokens/BAND.svg';
import { ReactComponent as TokenBat } from './tokens/BAT.svg';
import { ReactComponent as TokenBcd } from './tokens/BCD.svg';
import { ReactComponent as TokenBch } from './tokens/BCH.svg';
import { ReactComponent as TokenBcha } from './tokens/BCHA.svg';
import { ReactComponent as TokenBcn } from './tokens/BCN.svg';
import { ReactComponent as TokenBcna } from './tokens/BCNA.svg';
import { ReactComponent as TokenBelt } from './tokens/BELT.svg';
import { ReactComponent as TokenBhc } from './tokens/BHC.svg';
import { ReactComponent as TokenBit } from './tokens/BIT.svg';
import { ReactComponent as TokenBlast } from './tokens/BLAST.svg';
import { ReactComponent as TokenBld } from './tokens/BLD.svg';
import { ReactComponent as TokenBlox } from './tokens/BLOX.svg';
import { ReactComponent as TokenBlur } from './tokens/BLUR.svg';
import { ReactComponent as TokenBnb } from './tokens/BNB.svg';
import { ReactComponent as TokenBnt } from './tokens/BNT.svg';
import { ReactComponent as TokenBolt } from './tokens/BOLT.svg';
import { ReactComponent as TokenBoot } from './tokens/BOOT.svg';
import { ReactComponent as TokenBrains } from './tokens/BRAINS.svg';
import { ReactComponent as TokenBrkl } from './tokens/BRKL.svg';
import { ReactComponent as TokenBtc } from './tokens/BTC.svg';
import { ReactComponent as TokenBtcst } from './tokens/BTCST.svg';
import { ReactComponent as TokenBtg } from './tokens/BTG.svg';
import { ReactComponent as TokenBtm } from './tokens/BTM.svg';
import { ReactComponent as TokenBtmx } from './tokens/BTMX.svg';
import { ReactComponent as TokenBtsg } from './tokens/BTSG.svg';
import { ReactComponent as TokenBtt } from './tokens/BTT.svg';
import { ReactComponent as TokenBunny } from './tokens/BUNNY.svg';
import { ReactComponent as TokenBusd } from './tokens/BUSD.svg';
import { ReactComponent as TokenBusdt } from './tokens/BUSDT.svg';
import { ReactComponent as TokenC98 } from './tokens/C98.svg';
import { ReactComponent as TokenCake } from './tokens/CAKE.svg';
import { ReactComponent as TokenCanto } from './tokens/CANTO.svg';
import { ReactComponent as TokenCarb } from './tokens/CARB.svg';
import { ReactComponent as TokenCat } from './tokens/CAT.svg';
import { ReactComponent as TokenCel } from './tokens/CEL.svg';
import { ReactComponent as TokenCelo } from './tokens/CELO.svg';
import { ReactComponent as TokenCeth } from './tokens/CETH.svg';
import { ReactComponent as TokenCfx } from './tokens/CFX.svg';
import { ReactComponent as TokenCgas } from './tokens/CGAS.svg';
import { ReactComponent as TokenCheq } from './tokens/CHEQ.svg';
import { ReactComponent as TokenChsb } from './tokens/CHSB.svg';
import { ReactComponent as TokenCht } from './tokens/CHT.svg';
import { ReactComponent as TokenChz } from './tokens/CHZ.svg';
import { ReactComponent as TokenCkb } from './tokens/CKB.svg';
import { ReactComponent as TokenClp } from './tokens/CLP.svg';
import { ReactComponent as TokenCmdx } from './tokens/CMDX.svg';
import { ReactComponent as TokenCmst } from './tokens/CMST.svg';
import { ReactComponent as TokenCnt } from './tokens/CNT.svg';
import { ReactComponent as TokenCoin } from './tokens/COIN.svg';
import { ReactComponent as TokenComp } from './tokens/COMP.svg';
import { ReactComponent as TokenCrbrus } from './tokens/CRBRUS.svg';
import { ReactComponent as TokenCre } from './tokens/CRE.svg';
import { ReactComponent as TokenCro } from './tokens/CRO.svg';
import { ReactComponent as TokenCrv } from './tokens/CRV.svg';
import { ReactComponent as TokenCtk } from './tokens/CTK.svg';
import { ReactComponent as TokenCw } from './tokens/CW.svg';
import { ReactComponent as TokenDag } from './tokens/DAG.svg';
import { ReactComponent as TokenDai } from './tokens/DAI.svg';
import { ReactComponent as TokenDarc } from './tokens/DARC.svg';
import { ReactComponent as TokenDash } from './tokens/DASH.svg';
import { ReactComponent as TokenDbc } from './tokens/DBC.svg';
import { ReactComponent as TokenDcr } from './tokens/DCR.svg';
import { ReactComponent as TokenDec } from './tokens/DEC.svg';
import { ReactComponent as TokenDent } from './tokens/DENT.svg';
import { ReactComponent as TokenDgb } from './tokens/DGB.svg';
import { ReactComponent as TokenDig } from './tokens/DIG.svg';
import { ReactComponent as TokenDkt } from './tokens/DKT.svg';
import { ReactComponent as TokenDodo } from './tokens/DODO.svg';
import { ReactComponent as TokenDoge } from './tokens/DOGE.svg';
import { ReactComponent as TokenDot } from './tokens/DOT.svg';
import { ReactComponent as TokenDpx } from './tokens/DPX.svg';
import { ReactComponent as TokenDrft } from './tokens/DRFT.svg';
import { ReactComponent as TokenDsm } from './tokens/DSM.svg';
import { ReactComponent as TokenDvpn } from './tokens/DVPN.svg';
import { ReactComponent as TokenDydx } from './tokens/DYDX.svg';
import { ReactComponent as TokenDym } from './tokens/DYM.svg';
import { ReactComponent as TokenEeur } from './tokens/EEUR.svg';
import { ReactComponent as TokenEla } from './tokens/ELA.svg';
import { ReactComponent as TokenElf } from './tokens/ELF.svg';
import { ReactComponent as TokenEnj } from './tokens/ENJ.svg';
import { ReactComponent as TokenEns } from './tokens/ENS.svg';
import { ReactComponent as TokenEos } from './tokens/EOS.svg';
import { ReactComponent as TokenEps } from './tokens/EPS.svg';
import { ReactComponent as TokenEtc } from './tokens/ETC.svg';
import { ReactComponent as TokenEth } from './tokens/ETH.svg';
import { ReactComponent as TokenEtn } from './tokens/ETN.svg';
import { ReactComponent as TokenEuroc } from './tokens/EUROC.svg';
import { ReactComponent as TokenEut } from './tokens/EUT.svg';
import { ReactComponent as TokenEvmos } from './tokens/EVMOS.svg';
import { ReactComponent as TokenEwt } from './tokens/EWT.svg';
import { ReactComponent as TokenFees } from './tokens/FEES.svg';
import { ReactComponent as TokenFet } from './tokens/FET.svg';
import { ReactComponent as TokenFil } from './tokens/FIL.svg';
import { ReactComponent as TokenFis } from './tokens/FIS.svg';
import { ReactComponent as TokenFlix } from './tokens/FLIX.svg';
import { ReactComponent as TokenFlm } from './tokens/FLM.svg';
import { ReactComponent as TokenFlow } from './tokens/FLOW.svg';
import { ReactComponent as TokenFluid } from './tokens/FLUID.svg';
import { ReactComponent as TokenFluo } from './tokens/FLUO.svg';
import { ReactComponent as TokenFrank } from './tokens/FRANK.svg';
import { ReactComponent as TokenFtm } from './tokens/FTM.svg';
import { ReactComponent as TokenFtt } from './tokens/FTT.svg';
import { ReactComponent as TokenFttc } from './tokens/FTTC.svg';
import { ReactComponent as TokenFun } from './tokens/FUN.svg';
import { ReactComponent as TokenGala } from './tokens/GALA.svg';
import { ReactComponent as TokenGas } from './tokens/GAS.svg';
import { ReactComponent as TokenGbt } from './tokens/GBT.svg';
import { ReactComponent as TokenGlp } from './tokens/GLP.svg';
import { ReactComponent as TokenGm } from './tokens/GM.svg';
import { ReactComponent as TokenGmx } from './tokens/GMX.svg';
import { ReactComponent as TokenGno } from './tokens/GNO.svg';
import { ReactComponent as TokenGns } from './tokens/GNS.svg';
import { ReactComponent as TokenGrav } from './tokens/GRAV.svg';
import { ReactComponent as TokenGrt } from './tokens/GRT.svg';
import { ReactComponent as TokenGt } from './tokens/GT.svg';
import { ReactComponent as TokenGroupedUsd } from './tokens/Grouped USD.svg';
import { ReactComponent as TokenHbar } from './tokens/HBAR.svg';
import { ReactComponent as TokenHdn } from './tokens/HDN.svg';
import { ReactComponent as TokenHelmet } from './tokens/HELMET.svg';
import { ReactComponent as TokenHkt } from './tokens/HKT.svg';
import { ReactComponent as TokenHnt } from './tokens/HNT.svg';
import { ReactComponent as TokenHope } from './tokens/HOPE.svg';
import { ReactComponent as TokenHot } from './tokens/HOT.svg';
import { ReactComponent as TokenHt } from './tokens/HT.svg';
import { ReactComponent as TokenHuahua } from './tokens/HUAHUA.svg';
import { ReactComponent as TokenHuny } from './tokens/HUNY.svg';
import { ReactComponent as TokenHusd } from './tokens/HUSD.svg';
import { ReactComponent as TokenIbcx } from './tokens/IBCX.svg';
import { ReactComponent as TokenIcp } from './tokens/ICP.svg';
import { ReactComponent as TokenIcx } from './tokens/ICX.svg';
import { ReactComponent as TokenIdt } from './tokens/IDT.svg';
import { ReactComponent as TokenInj } from './tokens/INJ.svg';
import { ReactComponent as TokenInt } from './tokens/INT.svg';
import { ReactComponent as TokenIon } from './tokens/ION.svg';
import { ReactComponent as TokenIost } from './tokens/IOST.svg';
import { ReactComponent as TokenIotx } from './tokens/IOTX.svg';
import { ReactComponent as TokenIov } from './tokens/IOV.svg';
import { ReactComponent as TokenIris } from './tokens/IRIS.svg';
import { ReactComponent as TokenIxo } from './tokens/IXO.svg';
import { ReactComponent as TokenJpt } from './tokens/JPT.svg';
import { ReactComponent as TokenJto } from './tokens/JTO.svg';
import { ReactComponent as TokenJuno } from './tokens/JUNO.svg';
import { ReactComponent as TokenJup } from './tokens/JUP.svg';
import { ReactComponent as TokenKas } from './tokens/KAS.svg';
import { ReactComponent as TokenKcs } from './tokens/KCS.svg';
import { ReactComponent as TokenKlay } from './tokens/KLAY.svg';
import { ReactComponent as TokenKmd } from './tokens/KMD.svg';
import { ReactComponent as TokenKnc } from './tokens/KNC.svg';
import { ReactComponent as TokenKrt } from './tokens/KRT.svg';
import { ReactComponent as TokenKsm } from './tokens/KSM.svg';
import { ReactComponent as TokenKuji } from './tokens/KUJI.svg';
import { ReactComponent as TokenLdo } from './tokens/LDO.svg';
import { ReactComponent as TokenLeo } from './tokens/LEO.svg';
import { ReactComponent as TokenLet } from './tokens/LET.svg';
import { ReactComponent as TokenLike } from './tokens/LIKE.svg';
import { ReactComponent as TokenLink } from './tokens/LINK.svg';
import { ReactComponent as TokenLkt } from './tokens/LKT.svg';
import { ReactComponent as TokenLoom } from './tokens/LOOM.svg';
import { ReactComponent as TokenLoop } from './tokens/LOOP.svg';
import { ReactComponent as TokenLota } from './tokens/LOTA.svg';
import { ReactComponent as TokenLpt } from './tokens/LPT.svg';
import { ReactComponent as TokenLrc } from './tokens/LRC.svg';
import { ReactComponent as TokenLsi } from './tokens/LSI.svg';
import { ReactComponent as TokenLsk } from './tokens/LSK.svg';
import { ReactComponent as TokenLtc } from './tokens/LTC.svg';
import { ReactComponent as TokenLum } from './tokens/LUM.svg';
import { ReactComponent as TokenLuna } from './tokens/LUNA.svg';
import { ReactComponent as TokenLunax } from './tokens/LUNAX.svg';
import { ReactComponent as TokenLunc } from './tokens/LUNC.svg';
import { ReactComponent as TokenLuni } from './tokens/LUNI.svg';
import { ReactComponent as TokenLunr } from './tokens/LUNR.svg';
import { ReactComponent as TokenLuv } from './tokens/LUV.svg';
import { ReactComponent as TokenLiquidStakingIndex } from './tokens/Liquid Staking Index.svg';
import { ReactComponent as TokenMana } from './tokens/MANA.svg';
import { ReactComponent as TokenManta } from './tokens/MANTA.svg';
import { ReactComponent as TokenMarble } from './tokens/MARBLE.svg';
import { ReactComponent as TokenMath } from './tokens/MATH.svg';
import { ReactComponent as TokenMatic } from './tokens/MATIC.svg';
import { ReactComponent as TokenMdx } from './tokens/MDX.svg';
import { ReactComponent as TokenMed } from './tokens/MED.svg';
import { ReactComponent as TokenMeme } from './tokens/MEME.svg';
import { ReactComponent as TokenMiaw } from './tokens/MIAW.svg';
import { ReactComponent as TokenMina } from './tokens/MINA.svg';
import { ReactComponent as TokenMine } from './tokens/MINE.svg';
import { ReactComponent as TokenMiota } from './tokens/MIOTA.svg';
import { ReactComponent as TokenMir } from './tokens/MIR.svg';
import { ReactComponent as TokenMkr } from './tokens/MKR.svg';
import { ReactComponent as TokenMnt } from './tokens/MNT.svg';
import { ReactComponent as TokenMnta } from './tokens/MNTA.svg';
import { ReactComponent as TokenMntl } from './tokens/MNTL.svg';
import { ReactComponent as TokenMyt } from './tokens/MYT.svg';
import { ReactComponent as TokenNano } from './tokens/NANO.svg';
import { ReactComponent as TokenNas } from './tokens/NAS.svg';
import { ReactComponent as TokenNear } from './tokens/NEAR.svg';
import { ReactComponent as TokenNeo } from './tokens/NEO.svg';
import { ReactComponent as TokenNeta } from './tokens/NETA.svg';
import { ReactComponent as TokenNex } from './tokens/NEX.svg';
import { ReactComponent as TokenNexo } from './tokens/NEXO.svg';
import { ReactComponent as TokenNgm } from './tokens/NGM.svg';
import { ReactComponent as TokenNkn } from './tokens/NKN.svg';
import { ReactComponent as TokenNmr } from './tokens/NMR.svg';
import { ReactComponent as TokenNot } from './tokens/NOT.svg';
import { ReactComponent as TokenNote } from './tokens/NOTE.svg';
import { ReactComponent as TokenNpxs } from './tokens/NPXS.svg';
import { ReactComponent as TokenNtrn } from './tokens/NTRN.svg';
import { ReactComponent as TokenNxm } from './tokens/NXM.svg';
import { ReactComponent as TokenOcean } from './tokens/OCEAN.svg';
import { ReactComponent as TokenOgn } from './tokens/OGN.svg';
import { ReactComponent as TokenOkb } from './tokens/OKB.svg';
import { ReactComponent as TokenOkt } from './tokens/OKT.svg';
import { ReactComponent as TokenOmg } from './tokens/OMG.svg';
import { ReactComponent as TokenOmg_2 } from './tokens/OMG_2.svg';
import { ReactComponent as TokenOmi } from './tokens/OMI.svg';
import { ReactComponent as TokenOne } from './tokens/ONE.svg';
import { ReactComponent as TokenOnt } from './tokens/ONT.svg';
import { ReactComponent as TokenOpul } from './tokens/OPUL.svg';
import { ReactComponent as TokenOrion } from './tokens/ORION.svg';
import { ReactComponent as TokenOrne } from './tokens/ORNE.svg';
import { ReactComponent as TokenOsmo } from './tokens/OSMO.svg';
import { ReactComponent as TokenOxt } from './tokens/OXT.svg';
import { ReactComponent as TokenOxy } from './tokens/OXY.svg';
import { ReactComponent as TokenPax } from './tokens/PAX.svg';
import { ReactComponent as TokenPht } from './tokens/PHT.svg';
import { ReactComponent as TokenPlay } from './tokens/PLAY.svg';
import { ReactComponent as TokenPly } from './tokens/PLY.svg';
import { ReactComponent as TokenPoly } from './tokens/POLY.svg';
import { ReactComponent as TokenPort } from './tokens/PORT.svg';
import { ReactComponent as TokenProm } from './tokens/PROM.svg';
import { ReactComponent as TokenPsi } from './tokens/PSI.svg';
import { ReactComponent as TokenPstake } from './tokens/PSTAKE.svg';
import { ReactComponent as TokenPyth } from './tokens/PYTH.svg';
import { ReactComponent as TokenQck } from './tokens/QCK.svg';
import { ReactComponent as TokenQkc } from './tokens/QKC.svg';
import { ReactComponent as TokenQnt } from './tokens/QNT.svg';
import { ReactComponent as TokenQtum } from './tokens/QTUM.svg';
import { ReactComponent as TokenRay } from './tokens/RAY.svg';
import { ReactComponent as TokenRbn } from './tokens/RBN.svg';
import { ReactComponent as TokenReef } from './tokens/REEF.svg';
import { ReactComponent as TokenRegen } from './tokens/REGEN.svg';
import { ReactComponent as TokenRen } from './tokens/REN.svg';
import { ReactComponent as TokenRep } from './tokens/REP.svg';
import { ReactComponent as TokenRev } from './tokens/REV.svg';
import { ReactComponent as TokenRlb } from './tokens/RLB.svg';
import { ReactComponent as TokenRlc } from './tokens/RLC.svg';
import { ReactComponent as TokenRoar } from './tokens/ROAR.svg';
import { ReactComponent as TokenRowan } from './tokens/ROWAN.svg';
import { ReactComponent as TokenRsr } from './tokens/RSR.svg';
import { ReactComponent as TokenRune } from './tokens/RUNE.svg';
import { ReactComponent as TokenRvn } from './tokens/RVN.svg';
import { ReactComponent as TokenSafemoon } from './tokens/SAFEMOON.svg';
import { ReactComponent as TokenSand } from './tokens/SAND.svg';
import { ReactComponent as TokenSayve } from './tokens/SAYVE.svg';
import { ReactComponent as TokenSc } from './tokens/SC.svg';
import { ReactComponent as TokenScrt } from './tokens/SCRT.svg';
import { ReactComponent as TokenSdt } from './tokens/SDT.svg';
import { ReactComponent as TokenSei } from './tokens/SEI.svg';
import { ReactComponent as TokenSet } from './tokens/SET.svg';
import { ReactComponent as TokenSgt } from './tokens/SGT.svg';
import { ReactComponent as TokenShib } from './tokens/SHIB.svg';
import { ReactComponent as TokenSity } from './tokens/SITY.svg';
import { ReactComponent as TokenSnt } from './tokens/SNT.svg';
import { ReactComponent as TokenSnx } from './tokens/SNX.svg';
import { ReactComponent as TokenSol } from './tokens/SOL.svg';
import { ReactComponent as TokenSom } from './tokens/SOM.svg';
import { ReactComponent as TokenSomm } from './tokens/SOMM.svg';
import { ReactComponent as TokenSpec } from './tokens/SPEC.svg';
import { ReactComponent as TokenSrm } from './tokens/SRM.svg';
import { ReactComponent as TokenSrv } from './tokens/SRV.svg';
import { ReactComponent as TokenStars } from './tokens/STARS.svg';
import { ReactComponent as TokenSteem } from './tokens/STEEM.svg';
import { ReactComponent as TokenStmx } from './tokens/STMX.svg';
import { ReactComponent as TokenStorj } from './tokens/STORJ.svg';
import { ReactComponent as TokenStrax } from './tokens/STRAX.svg';
import { ReactComponent as TokenStrd } from './tokens/STRD.svg';
import { ReactComponent as TokenStream } from './tokens/STREAM.svg';
import { ReactComponent as TokenStrk } from './tokens/STRK.svg';
import { ReactComponent as TokenStt } from './tokens/STT.svg';
import { ReactComponent as TokenStx } from './tokens/STX.svg';
import { ReactComponent as TokenSushi } from './tokens/SUSHI.svg';
import { ReactComponent as TokenSwthLegacy } from './tokens/SWTH-LEGACY.svg';
import { ReactComponent as TokenSwth } from './tokens/SWTH.svg';
import { ReactComponent as TokenSxp } from './tokens/SXP.svg';
import { ReactComponent as TokenTel } from './tokens/TEL.svg';
import { ReactComponent as TokenTfuel } from './tokens/TFUEL.svg';
import { ReactComponent as TokenTheta } from './tokens/THETA.svg';
import { ReactComponent as TokenTht } from './tokens/THT.svg';
import { ReactComponent as TokenTia } from './tokens/TIA.svg';
import { ReactComponent as TokenTick } from './tokens/TICK.svg';
import { ReactComponent as TokenTitan } from './tokens/TITAN.svg';
import { ReactComponent as TokenTland } from './tokens/TLAND.svg';
import { ReactComponent as TokenTlm } from './tokens/TLM.svg';
import { ReactComponent as TokenTomo } from './tokens/TOMO.svg';
import { ReactComponent as TokenTon } from './tokens/TON.svg';
import { ReactComponent as TokenTpc } from './tokens/TPC.svg';
import { ReactComponent as TokenTraxx } from './tokens/TRAXX.svg';
import { ReactComponent as TokenTrb } from './tokens/TRB.svg';
import { ReactComponent as TokenTru } from './tokens/TRU.svg';
import { ReactComponent as TokenTrx } from './tokens/TRX.svg';
import { ReactComponent as TokenTtt } from './tokens/TTT.svg';
import { ReactComponent as TokenTusd } from './tokens/TUSD.svg';
import { ReactComponent as TokenTwd } from './tokens/TWD.svg';
import { ReactComponent as TokenTwt } from './tokens/TWT.svg';
import { ReactComponent as TokenToken } from './tokens/Token.svg';
import { ReactComponent as TokenUbq } from './tokens/UBQ.svg';
import { ReactComponent as TokenUmee } from './tokens/UMEE.svg';
import { ReactComponent as TokenUna } from './tokens/UNA.svg';
import { ReactComponent as TokenUni } from './tokens/UNI.svg';
import { ReactComponent as TokenUos } from './tokens/UOS.svg';
import { ReactComponent as TokenUscMinted } from './tokens/USC-Minted.svg';
import { ReactComponent as TokenUsc } from './tokens/USC.svg';
import { ReactComponent as TokenUsd } from './tokens/USD.svg';
import { ReactComponent as TokenUsdc } from './tokens/USDC.svg';
import { ReactComponent as TokenUsdp } from './tokens/USDP.svg';
import { ReactComponent as TokenUsdt } from './tokens/USDT.svg';
import { ReactComponent as TokenUsk } from './tokens/USK.svg';
import { ReactComponent as TokenUst } from './tokens/UST.svg';
import { ReactComponent as TokenVdl } from './tokens/VDL.svg';
import { ReactComponent as TokenVet } from './tokens/VET.svg';
import { ReactComponent as TokenVkr } from './tokens/VKR.svg';
import { ReactComponent as TokenVrtx } from './tokens/VRTX.svg';
import { ReactComponent as TokenWave } from './tokens/WAVE.svg';
import { ReactComponent as TokenWbnb } from './tokens/WBNB.svg';
import { ReactComponent as TokenWbtc } from './tokens/WBTC.svg';
import { ReactComponent as TokenWeth } from './tokens/WETH.svg';
import { ReactComponent as TokenWhale } from './tokens/WHALE.svg';
import { ReactComponent as TokenWin } from './tokens/WIN.svg';
import { ReactComponent as TokenWld } from './tokens/WLD.svg';
import { ReactComponent as TokenWmatic } from './tokens/WMATIC.svg';
import { ReactComponent as TokenWrx } from './tokens/WRX.svg';
import { ReactComponent as TokenXcad } from './tokens/XCAD.svg';
import { ReactComponent as TokenXdc } from './tokens/XDC.svg';
import { ReactComponent as TokenXem } from './tokens/XEM.svg';
import { ReactComponent as TokenXki } from './tokens/XKI.svg';
import { ReactComponent as TokenXlm } from './tokens/XLM.svg';
import { ReactComponent as TokenXmr } from './tokens/XMR.svg';
import { ReactComponent as TokenXprt } from './tokens/XPRT.svg';
import { ReactComponent as TokenXrp } from './tokens/XRP.svg';
import { ReactComponent as TokenXsgd } from './tokens/XSGD.svg';
import { ReactComponent as TokenXtra } from './tokens/XTRA.svg';
import { ReactComponent as TokenXtz } from './tokens/XTZ.svg';
import { ReactComponent as TokenXvg } from './tokens/XVG.svg';
import { ReactComponent as TokenXvs } from './tokens/XVS.svg';
import { ReactComponent as TokenYam } from './tokens/YAM.svg';
import { ReactComponent as TokenYfi } from './tokens/YFI.svg';
import { ReactComponent as TokenYieldUsd } from './tokens/Yield USD.svg';
import { ReactComponent as TokenYieldusd } from './tokens/YieldUSD.svg';
import { ReactComponent as TokenZch } from './tokens/ZCH.svg';
import { ReactComponent as TokenZec } from './tokens/ZEC.svg';
import { ReactComponent as TokenZen } from './tokens/ZEN.svg';
import { ReactComponent as TokenZil } from './tokens/ZIL.svg';
import { ReactComponent as TokenZro } from './tokens/ZRO.svg';
import { ReactComponent as TokenZrx } from './tokens/ZRX.svg';
import { ReactComponent as TokenZwap } from './tokens/ZWAP.svg';
import { ReactComponent as TokenAmpkuji } from './tokens/ampKUJI.svg';
import { ReactComponent as TokenAmpluna } from './tokens/ampLUNA.svg';
import { ReactComponent as TokenAxlusdc } from './tokens/axlUSDC.svg';
import { ReactComponent as TokenBcfx } from './tokens/bCFX.svg';
import { ReactComponent as TokenBneo } from './tokens/bNEO.svg';
import { ReactComponent as TokenCglp } from './tokens/cGLP.svg';
import { ReactComponent as TokenCusd } from './tokens/cUSD.svg';
import { ReactComponent as TokenDxcad } from './tokens/dXCAD.svg';
import { ReactComponent as TokenEgld } from './tokens/eGLD.svg';
import { ReactComponent as TokenEplay } from './tokens/ePLAY.svg';
import { ReactComponent as TokenEsfluo } from './tokens/esFLUO.svg';
import { ReactComponent as TokenGzil } from './tokens/gZIL.svg';
import { ReactComponent as TokenIusd } from './tokens/iUSD.svg';
import { ReactComponent as TokenMilktia } from './tokens/milkTIA.svg';
import { ReactComponent as TokenNneo } from './tokens/nNEO.svg';
import { ReactComponent as TokenRatom } from './tokens/rATOM.svg';
import { ReactComponent as TokenRswth } from './tokens/rSWTH.svg';
import { ReactComponent as TokenStatom } from './tokens/stATOM.svg';
import { ReactComponent as TokenSteth } from './tokens/stETH.svg';
import { ReactComponent as TokenStevmos } from './tokens/stEVMOS.svg';
import { ReactComponent as TokenStfluo } from './tokens/stFLUO.svg';
import { ReactComponent as TokenStibcx } from './tokens/stIBCX.svg';
import { ReactComponent as TokenStjuno } from './tokens/stJUNO.svg';
import { ReactComponent as TokenStluna } from './tokens/stLUNA.svg';
import { ReactComponent as TokenStokt } from './tokens/stOKT.svg';
import { ReactComponent as TokenStosmo } from './tokens/stOSMO.svg';
import { ReactComponent as TokenStstars } from './tokens/stSTARS.svg';
import { ReactComponent as TokenStzil } from './tokens/stZIL.svg';
import { ReactComponent as TokenStkatom } from './tokens/stkATOM.svg';
import { ReactComponent as TokenVzwap } from './tokens/vZWAP.svg';
import { ReactComponent as TokenVefluo } from './tokens/veFLUO.svg';
import { ReactComponent as TokenWkas } from './tokens/wKAS.svg';
import { ReactComponent as TokenWsteth } from './tokens/wstETH.svg';

export const Token1inchIcon = withIconProps(Token1inch);
export const TokenAaveIcon = withIconProps(TokenAave);
export const TokenAdaIcon = withIconProps(TokenAda);
export const TokenAevoIcon = withIconProps(TokenAevo);
export const TokenAgiIcon = withIconProps(TokenAgi);
export const TokenAkroIcon = withIconProps(TokenAkro);
export const TokenAktIcon = withIconProps(TokenAkt);
export const TokenAlgoIcon = withIconProps(TokenAlgo);
export const TokenAlphaIcon = withIconProps(TokenAlpha);
export const TokenAmpIcon = withIconProps(TokenAmp);
export const TokenAncIcon = withIconProps(TokenAnc);
export const TokenAnkrIcon = withIconProps(TokenAnkr);
export const TokenAntIcon = withIconProps(TokenAnt);
export const TokenAnyIcon = withIconProps(TokenAny);
export const TokenApeIcon = withIconProps(TokenApe);
export const TokenApolloIcon = withIconProps(TokenApollo);
export const TokenArIcon = withIconProps(TokenAr);
export const TokenArbIcon = withIconProps(TokenArb);
export const TokenAsaIcon = withIconProps(TokenAsa);
export const TokenAstroIcon = withIconProps(TokenAstro);
export const TokenAtomIcon = withIconProps(TokenAtom);
export const TokenAudioIcon = withIconProps(TokenAudio);
export const TokenAutIcon = withIconProps(TokenAut);
export const TokenAvaIcon = withIconProps(TokenAva);
export const TokenAvaxIcon = withIconProps(TokenAvax);
export const TokenAxlIcon = withIconProps(TokenAxl);
export const TokenAxsIcon = withIconProps(TokenAxs);
export const TokenAxtIcon = withIconProps(TokenAxt);
export const TokenBakeIcon = withIconProps(TokenBake);
export const TokenBalIcon = withIconProps(TokenBal);
export const TokenBandIcon = withIconProps(TokenBand);
export const TokenBatIcon = withIconProps(TokenBat);
export const TokenBcdIcon = withIconProps(TokenBcd);
export const TokenBchIcon = withIconProps(TokenBch);
export const TokenBchaIcon = withIconProps(TokenBcha);
export const TokenBcnIcon = withIconProps(TokenBcn);
export const TokenBcnaIcon = withIconProps(TokenBcna);
export const TokenBeltIcon = withIconProps(TokenBelt);
export const TokenBhcIcon = withIconProps(TokenBhc);
export const TokenBitIcon = withIconProps(TokenBit);
export const TokenBlastIcon = withIconProps(TokenBlast);
export const TokenBldIcon = withIconProps(TokenBld);
export const TokenBloxIcon = withIconProps(TokenBlox);
export const TokenBlurIcon = withIconProps(TokenBlur);
export const TokenBnbIcon = withIconProps(TokenBnb);
export const TokenBntIcon = withIconProps(TokenBnt);
export const TokenBoltIcon = withIconProps(TokenBolt);
export const TokenBootIcon = withIconProps(TokenBoot);
export const TokenBrainsIcon = withIconProps(TokenBrains);
export const TokenBrklIcon = withIconProps(TokenBrkl);
export const TokenBtcIcon = withIconProps(TokenBtc);
export const TokenBtcstIcon = withIconProps(TokenBtcst);
export const TokenBtgIcon = withIconProps(TokenBtg);
export const TokenBtmIcon = withIconProps(TokenBtm);
export const TokenBtmxIcon = withIconProps(TokenBtmx);
export const TokenBtsgIcon = withIconProps(TokenBtsg);
export const TokenBttIcon = withIconProps(TokenBtt);
export const TokenBunnyIcon = withIconProps(TokenBunny);
export const TokenBusdIcon = withIconProps(TokenBusd);
export const TokenBusdtIcon = withIconProps(TokenBusdt);
export const TokenC98Icon = withIconProps(TokenC98);
export const TokenCakeIcon = withIconProps(TokenCake);
export const TokenCantoIcon = withIconProps(TokenCanto);
export const TokenCarbIcon = withIconProps(TokenCarb);
export const TokenCatIcon = withIconProps(TokenCat);
export const TokenCelIcon = withIconProps(TokenCel);
export const TokenCeloIcon = withIconProps(TokenCelo);
export const TokenCethIcon = withIconProps(TokenCeth);
export const TokenCfxIcon = withIconProps(TokenCfx);
export const TokenCgasIcon = withIconProps(TokenCgas);
export const TokenCheqIcon = withIconProps(TokenCheq);
export const TokenChsbIcon = withIconProps(TokenChsb);
export const TokenChtIcon = withIconProps(TokenCht);
export const TokenChzIcon = withIconProps(TokenChz);
export const TokenCkbIcon = withIconProps(TokenCkb);
export const TokenClpIcon = withIconProps(TokenClp);
export const TokenCmdxIcon = withIconProps(TokenCmdx);
export const TokenCmstIcon = withIconProps(TokenCmst);
export const TokenCntIcon = withIconProps(TokenCnt);
export const TokenCoinIcon = withIconProps(TokenCoin);
export const TokenCompIcon = withIconProps(TokenComp);
export const TokenCrbrusIcon = withIconProps(TokenCrbrus);
export const TokenCreIcon = withIconProps(TokenCre);
export const TokenCroIcon = withIconProps(TokenCro);
export const TokenCrvIcon = withIconProps(TokenCrv);
export const TokenCtkIcon = withIconProps(TokenCtk);
export const TokenCwIcon = withIconProps(TokenCw);
export const TokenDagIcon = withIconProps(TokenDag);
export const TokenDaiIcon = withIconProps(TokenDai);
export const TokenDarcIcon = withIconProps(TokenDarc);
export const TokenDashIcon = withIconProps(TokenDash);
export const TokenDbcIcon = withIconProps(TokenDbc);
export const TokenDcrIcon = withIconProps(TokenDcr);
export const TokenDecIcon = withIconProps(TokenDec);
export const TokenDentIcon = withIconProps(TokenDent);
export const TokenDgbIcon = withIconProps(TokenDgb);
export const TokenDigIcon = withIconProps(TokenDig);
export const TokenDktIcon = withIconProps(TokenDkt);
export const TokenDodoIcon = withIconProps(TokenDodo);
export const TokenDogeIcon = withIconProps(TokenDoge);
export const TokenDotIcon = withIconProps(TokenDot);
export const TokenDpxIcon = withIconProps(TokenDpx);
export const TokenDrftIcon = withIconProps(TokenDrft);
export const TokenDsmIcon = withIconProps(TokenDsm);
export const TokenDvpnIcon = withIconProps(TokenDvpn);
export const TokenDydxIcon = withIconProps(TokenDydx);
export const TokenDymIcon = withIconProps(TokenDym);
export const TokenEeurIcon = withIconProps(TokenEeur);
export const TokenElaIcon = withIconProps(TokenEla);
export const TokenElfIcon = withIconProps(TokenElf);
export const TokenEnjIcon = withIconProps(TokenEnj);
export const TokenEnsIcon = withIconProps(TokenEns);
export const TokenEosIcon = withIconProps(TokenEos);
export const TokenEpsIcon = withIconProps(TokenEps);
export const TokenEtcIcon = withIconProps(TokenEtc);
export const TokenEthIcon = withIconProps(TokenEth);
export const TokenEtnIcon = withIconProps(TokenEtn);
export const TokenEurocIcon = withIconProps(TokenEuroc);
export const TokenEutIcon = withIconProps(TokenEut);
export const TokenEvmosIcon = withIconProps(TokenEvmos);
export const TokenEwtIcon = withIconProps(TokenEwt);
export const TokenFeesIcon = withIconProps(TokenFees);
export const TokenFetIcon = withIconProps(TokenFet);
export const TokenFilIcon = withIconProps(TokenFil);
export const TokenFisIcon = withIconProps(TokenFis);
export const TokenFlixIcon = withIconProps(TokenFlix);
export const TokenFlmIcon = withIconProps(TokenFlm);
export const TokenFlowIcon = withIconProps(TokenFlow);
export const TokenFluidIcon = withIconProps(TokenFluid);
export const TokenFluoIcon = withIconProps(TokenFluo);
export const TokenFrankIcon = withIconProps(TokenFrank);
export const TokenFtmIcon = withIconProps(TokenFtm);
export const TokenFttIcon = withIconProps(TokenFtt);
export const TokenFttcIcon = withIconProps(TokenFttc);
export const TokenFunIcon = withIconProps(TokenFun);
export const TokenGalaIcon = withIconProps(TokenGala);
export const TokenGasIcon = withIconProps(TokenGas);
export const TokenGbtIcon = withIconProps(TokenGbt);
export const TokenGlpIcon = withIconProps(TokenGlp);
export const TokenGmIcon = withIconProps(TokenGm);
export const TokenGmxIcon = withIconProps(TokenGmx);
export const TokenGnoIcon = withIconProps(TokenGno);
export const TokenGnsIcon = withIconProps(TokenGns);
export const TokenGravIcon = withIconProps(TokenGrav);
export const TokenGrtIcon = withIconProps(TokenGrt);
export const TokenGtIcon = withIconProps(TokenGt);
export const TokenGroupedUsdIcon = withIconProps(TokenGroupedUsd);
export const TokenHbarIcon = withIconProps(TokenHbar);
export const TokenHdnIcon = withIconProps(TokenHdn);
export const TokenHelmetIcon = withIconProps(TokenHelmet);
export const TokenHktIcon = withIconProps(TokenHkt);
export const TokenHntIcon = withIconProps(TokenHnt);
export const TokenHopeIcon = withIconProps(TokenHope);
export const TokenHotIcon = withIconProps(TokenHot);
export const TokenHtIcon = withIconProps(TokenHt);
export const TokenHuahuaIcon = withIconProps(TokenHuahua);
export const TokenHunyIcon = withIconProps(TokenHuny);
export const TokenHusdIcon = withIconProps(TokenHusd);
export const TokenIbcxIcon = withIconProps(TokenIbcx);
export const TokenIcpIcon = withIconProps(TokenIcp);
export const TokenIcxIcon = withIconProps(TokenIcx);
export const TokenIdtIcon = withIconProps(TokenIdt);
export const TokenInjIcon = withIconProps(TokenInj);
export const TokenIntIcon = withIconProps(TokenInt);
export const TokenIonIcon = withIconProps(TokenIon);
export const TokenIostIcon = withIconProps(TokenIost);
export const TokenIotxIcon = withIconProps(TokenIotx);
export const TokenIovIcon = withIconProps(TokenIov);
export const TokenIrisIcon = withIconProps(TokenIris);
export const TokenIxoIcon = withIconProps(TokenIxo);
export const TokenJptIcon = withIconProps(TokenJpt);
export const TokenJtoIcon = withIconProps(TokenJto);
export const TokenJunoIcon = withIconProps(TokenJuno);
export const TokenJupIcon = withIconProps(TokenJup);
export const TokenKasIcon = withIconProps(TokenKas);
export const TokenKcsIcon = withIconProps(TokenKcs);
export const TokenKlayIcon = withIconProps(TokenKlay);
export const TokenKmdIcon = withIconProps(TokenKmd);
export const TokenKncIcon = withIconProps(TokenKnc);
export const TokenKrtIcon = withIconProps(TokenKrt);
export const TokenKsmIcon = withIconProps(TokenKsm);
export const TokenKujiIcon = withIconProps(TokenKuji);
export const TokenLdoIcon = withIconProps(TokenLdo);
export const TokenLeoIcon = withIconProps(TokenLeo);
export const TokenLetIcon = withIconProps(TokenLet);
export const TokenLikeIcon = withIconProps(TokenLike);
export const TokenLinkIcon = withIconProps(TokenLink);
export const TokenLktIcon = withIconProps(TokenLkt);
export const TokenLoomIcon = withIconProps(TokenLoom);
export const TokenLoopIcon = withIconProps(TokenLoop);
export const TokenLotaIcon = withIconProps(TokenLota);
export const TokenLptIcon = withIconProps(TokenLpt);
export const TokenLrcIcon = withIconProps(TokenLrc);
export const TokenLsiIcon = withIconProps(TokenLsi);
export const TokenLskIcon = withIconProps(TokenLsk);
export const TokenLtcIcon = withIconProps(TokenLtc);
export const TokenLumIcon = withIconProps(TokenLum);
export const TokenLunaIcon = withIconProps(TokenLuna);
export const TokenLunaxIcon = withIconProps(TokenLunax);
export const TokenLuncIcon = withIconProps(TokenLunc);
export const TokenLuniIcon = withIconProps(TokenLuni);
export const TokenLunrIcon = withIconProps(TokenLunr);
export const TokenLuvIcon = withIconProps(TokenLuv);
export const TokenLiquidStakingIndexIcon = withIconProps(TokenLiquidStakingIndex);
export const TokenManaIcon = withIconProps(TokenMana);
export const TokenMantaIcon = withIconProps(TokenManta);
export const TokenMarbleIcon = withIconProps(TokenMarble);
export const TokenMathIcon = withIconProps(TokenMath);
export const TokenMaticIcon = withIconProps(TokenMatic);
export const TokenMdxIcon = withIconProps(TokenMdx);
export const TokenMedIcon = withIconProps(TokenMed);
export const TokenMemeIcon = withIconProps(TokenMeme);
export const TokenMiawIcon = withIconProps(TokenMiaw);
export const TokenMinaIcon = withIconProps(TokenMina);
export const TokenMineIcon = withIconProps(TokenMine);
export const TokenMiotaIcon = withIconProps(TokenMiota);
export const TokenMirIcon = withIconProps(TokenMir);
export const TokenMkrIcon = withIconProps(TokenMkr);
export const TokenMntIcon = withIconProps(TokenMnt);
export const TokenMntaIcon = withIconProps(TokenMnta);
export const TokenMntlIcon = withIconProps(TokenMntl);
export const TokenMytIcon = withIconProps(TokenMyt);
export const TokenNanoIcon = withIconProps(TokenNano);
export const TokenNasIcon = withIconProps(TokenNas);
export const TokenNearIcon = withIconProps(TokenNear);
export const TokenNeoIcon = withIconProps(TokenNeo);
export const TokenNetaIcon = withIconProps(TokenNeta);
export const TokenNexIcon = withIconProps(TokenNex);
export const TokenNexoIcon = withIconProps(TokenNexo);
export const TokenNgmIcon = withIconProps(TokenNgm);
export const TokenNknIcon = withIconProps(TokenNkn);
export const TokenNmrIcon = withIconProps(TokenNmr);
export const TokenNotIcon = withIconProps(TokenNot);
export const TokenNoteIcon = withIconProps(TokenNote);
export const TokenNpxsIcon = withIconProps(TokenNpxs);
export const TokenNtrnIcon = withIconProps(TokenNtrn);
export const TokenNxmIcon = withIconProps(TokenNxm);
export const TokenOceanIcon = withIconProps(TokenOcean);
export const TokenOgnIcon = withIconProps(TokenOgn);
export const TokenOkbIcon = withIconProps(TokenOkb);
export const TokenOktIcon = withIconProps(TokenOkt);
export const TokenOmgIcon = withIconProps(TokenOmg);
export const TokenOmg_2Icon = withIconProps(TokenOmg_2);
export const TokenOmiIcon = withIconProps(TokenOmi);
export const TokenOneIcon = withIconProps(TokenOne);
export const TokenOntIcon = withIconProps(TokenOnt);
export const TokenOpulIcon = withIconProps(TokenOpul);
export const TokenOrionIcon = withIconProps(TokenOrion);
export const TokenOrneIcon = withIconProps(TokenOrne);
export const TokenOsmoIcon = withIconProps(TokenOsmo);
export const TokenOxtIcon = withIconProps(TokenOxt);
export const TokenOxyIcon = withIconProps(TokenOxy);
export const TokenPaxIcon = withIconProps(TokenPax);
export const TokenPhtIcon = withIconProps(TokenPht);
export const TokenPlayIcon = withIconProps(TokenPlay);
export const TokenPlyIcon = withIconProps(TokenPly);
export const TokenPolyIcon = withIconProps(TokenPoly);
export const TokenPortIcon = withIconProps(TokenPort);
export const TokenPromIcon = withIconProps(TokenProm);
export const TokenPsiIcon = withIconProps(TokenPsi);
export const TokenPstakeIcon = withIconProps(TokenPstake);
export const TokenPythIcon = withIconProps(TokenPyth);
export const TokenQckIcon = withIconProps(TokenQck);
export const TokenQkcIcon = withIconProps(TokenQkc);
export const TokenQntIcon = withIconProps(TokenQnt);
export const TokenQtumIcon = withIconProps(TokenQtum);
export const TokenRayIcon = withIconProps(TokenRay);
export const TokenRbnIcon = withIconProps(TokenRbn);
export const TokenReefIcon = withIconProps(TokenReef);
export const TokenRegenIcon = withIconProps(TokenRegen);
export const TokenRenIcon = withIconProps(TokenRen);
export const TokenRepIcon = withIconProps(TokenRep);
export const TokenRevIcon = withIconProps(TokenRev);
export const TokenRlbIcon = withIconProps(TokenRlb);
export const TokenRlcIcon = withIconProps(TokenRlc);
export const TokenRoarIcon = withIconProps(TokenRoar);
export const TokenRowanIcon = withIconProps(TokenRowan);
export const TokenRsrIcon = withIconProps(TokenRsr);
export const TokenRuneIcon = withIconProps(TokenRune);
export const TokenRvnIcon = withIconProps(TokenRvn);
export const TokenSafemoonIcon = withIconProps(TokenSafemoon);
export const TokenSandIcon = withIconProps(TokenSand);
export const TokenSayveIcon = withIconProps(TokenSayve);
export const TokenScIcon = withIconProps(TokenSc);
export const TokenScrtIcon = withIconProps(TokenScrt);
export const TokenSdtIcon = withIconProps(TokenSdt);
export const TokenSeiIcon = withIconProps(TokenSei);
export const TokenSetIcon = withIconProps(TokenSet);
export const TokenSgtIcon = withIconProps(TokenSgt);
export const TokenShibIcon = withIconProps(TokenShib);
export const TokenSityIcon = withIconProps(TokenSity);
export const TokenSntIcon = withIconProps(TokenSnt);
export const TokenSnxIcon = withIconProps(TokenSnx);
export const TokenSolIcon = withIconProps(TokenSol);
export const TokenSomIcon = withIconProps(TokenSom);
export const TokenSommIcon = withIconProps(TokenSomm);
export const TokenSpecIcon = withIconProps(TokenSpec);
export const TokenSrmIcon = withIconProps(TokenSrm);
export const TokenSrvIcon = withIconProps(TokenSrv);
export const TokenStarsIcon = withIconProps(TokenStars);
export const TokenSteemIcon = withIconProps(TokenSteem);
export const TokenStmxIcon = withIconProps(TokenStmx);
export const TokenStorjIcon = withIconProps(TokenStorj);
export const TokenStraxIcon = withIconProps(TokenStrax);
export const TokenStrdIcon = withIconProps(TokenStrd);
export const TokenStreamIcon = withIconProps(TokenStream);
export const TokenStrkIcon = withIconProps(TokenStrk);
export const TokenSttIcon = withIconProps(TokenStt);
export const TokenStxIcon = withIconProps(TokenStx);
export const TokenSushiIcon = withIconProps(TokenSushi);
export const TokenSwthLegacyIcon = withIconProps(TokenSwthLegacy);
export const TokenSwthIcon = withIconProps(TokenSwth);
export const TokenSxpIcon = withIconProps(TokenSxp);
export const TokenTelIcon = withIconProps(TokenTel);
export const TokenTfuelIcon = withIconProps(TokenTfuel);
export const TokenThetaIcon = withIconProps(TokenTheta);
export const TokenThtIcon = withIconProps(TokenTht);
export const TokenTiaIcon = withIconProps(TokenTia);
export const TokenTickIcon = withIconProps(TokenTick);
export const TokenTitanIcon = withIconProps(TokenTitan);
export const TokenTlandIcon = withIconProps(TokenTland);
export const TokenTlmIcon = withIconProps(TokenTlm);
export const TokenTomoIcon = withIconProps(TokenTomo);
export const TokenTonIcon = withIconProps(TokenTon);
export const TokenTpcIcon = withIconProps(TokenTpc);
export const TokenTraxxIcon = withIconProps(TokenTraxx);
export const TokenTrbIcon = withIconProps(TokenTrb);
export const TokenTruIcon = withIconProps(TokenTru);
export const TokenTrxIcon = withIconProps(TokenTrx);
export const TokenTttIcon = withIconProps(TokenTtt);
export const TokenTusdIcon = withIconProps(TokenTusd);
export const TokenTwdIcon = withIconProps(TokenTwd);
export const TokenTwtIcon = withIconProps(TokenTwt);
export const TokenTokenIcon = withIconProps(TokenToken);
export const TokenUbqIcon = withIconProps(TokenUbq);
export const TokenUmeeIcon = withIconProps(TokenUmee);
export const TokenUnaIcon = withIconProps(TokenUna);
export const TokenUniIcon = withIconProps(TokenUni);
export const TokenUosIcon = withIconProps(TokenUos);
export const TokenUscMintedIcon = withIconProps(TokenUscMinted);
export const TokenUscIcon = withIconProps(TokenUsc);
export const TokenUsdIcon = withIconProps(TokenUsd);
export const TokenUsdcIcon = withIconProps(TokenUsdc);
export const TokenUsdpIcon = withIconProps(TokenUsdp);
export const TokenUsdtIcon = withIconProps(TokenUsdt);
export const TokenUskIcon = withIconProps(TokenUsk);
export const TokenUstIcon = withIconProps(TokenUst);
export const TokenVdlIcon = withIconProps(TokenVdl);
export const TokenVetIcon = withIconProps(TokenVet);
export const TokenVkrIcon = withIconProps(TokenVkr);
export const TokenVrtxIcon = withIconProps(TokenVrtx);
export const TokenWaveIcon = withIconProps(TokenWave);
export const TokenWbnbIcon = withIconProps(TokenWbnb);
export const TokenWbtcIcon = withIconProps(TokenWbtc);
export const TokenWethIcon = withIconProps(TokenWeth);
export const TokenWhaleIcon = withIconProps(TokenWhale);
export const TokenWinIcon = withIconProps(TokenWin);
export const TokenWldIcon = withIconProps(TokenWld);
export const TokenWmaticIcon = withIconProps(TokenWmatic);
export const TokenWrxIcon = withIconProps(TokenWrx);
export const TokenXcadIcon = withIconProps(TokenXcad);
export const TokenXdcIcon = withIconProps(TokenXdc);
export const TokenXemIcon = withIconProps(TokenXem);
export const TokenXkiIcon = withIconProps(TokenXki);
export const TokenXlmIcon = withIconProps(TokenXlm);
export const TokenXmrIcon = withIconProps(TokenXmr);
export const TokenXprtIcon = withIconProps(TokenXprt);
export const TokenXrpIcon = withIconProps(TokenXrp);
export const TokenXsgdIcon = withIconProps(TokenXsgd);
export const TokenXtraIcon = withIconProps(TokenXtra);
export const TokenXtzIcon = withIconProps(TokenXtz);
export const TokenXvgIcon = withIconProps(TokenXvg);
export const TokenXvsIcon = withIconProps(TokenXvs);
export const TokenYamIcon = withIconProps(TokenYam);
export const TokenYfiIcon = withIconProps(TokenYfi);
export const TokenYieldUsdIcon = withIconProps(TokenYieldUsd);
export const TokenYieldusdIcon = withIconProps(TokenYieldusd);
export const TokenZchIcon = withIconProps(TokenZch);
export const TokenZecIcon = withIconProps(TokenZec);
export const TokenZenIcon = withIconProps(TokenZen);
export const TokenZilIcon = withIconProps(TokenZil);
export const TokenZroIcon = withIconProps(TokenZro);
export const TokenZrxIcon = withIconProps(TokenZrx);
export const TokenZwapIcon = withIconProps(TokenZwap);
export const TokenAmpkujiIcon = withIconProps(TokenAmpkuji);
export const TokenAmplunaIcon = withIconProps(TokenAmpluna);
export const TokenAxlusdcIcon = withIconProps(TokenAxlusdc);
export const TokenBcfxIcon = withIconProps(TokenBcfx);
export const TokenBneoIcon = withIconProps(TokenBneo);
export const TokenCglpIcon = withIconProps(TokenCglp);
export const TokenCusdIcon = withIconProps(TokenCusd);
export const TokenDxcadIcon = withIconProps(TokenDxcad);
export const TokenEgldIcon = withIconProps(TokenEgld);
export const TokenEplayIcon = withIconProps(TokenEplay);
export const TokenEsfluoIcon = withIconProps(TokenEsfluo);
export const TokenGzilIcon = withIconProps(TokenGzil);
export const TokenIusdIcon = withIconProps(TokenIusd);
export const TokenMilktiaIcon = withIconProps(TokenMilktia);
export const TokenNneoIcon = withIconProps(TokenNneo);
export const TokenRatomIcon = withIconProps(TokenRatom);
export const TokenRswthIcon = withIconProps(TokenRswth);
export const TokenStatomIcon = withIconProps(TokenStatom);
export const TokenStethIcon = withIconProps(TokenSteth);
export const TokenStevmosIcon = withIconProps(TokenStevmos);
export const TokenStfluoIcon = withIconProps(TokenStfluo);
export const TokenStibcxIcon = withIconProps(TokenStibcx);
export const TokenStjunoIcon = withIconProps(TokenStjuno);
export const TokenStlunaIcon = withIconProps(TokenStluna);
export const TokenStoktIcon = withIconProps(TokenStokt);
export const TokenStosmoIcon = withIconProps(TokenStosmo);
export const TokenStstarsIcon = withIconProps(TokenStstars);
export const TokenStzilIcon = withIconProps(TokenStzil);
export const TokenStkatomIcon = withIconProps(TokenStkatom);
export const TokenVzwapIcon = withIconProps(TokenVzwap);
export const TokenVefluoIcon = withIconProps(TokenVefluo);
export const TokenWkasIcon = withIconProps(TokenWkas);
export const TokenWstethIcon = withIconProps(TokenWsteth);
